gText_Birch_Welcome:: @ 82C897B
	.string "So.\l"
	.string "I take it you're ready to talk?\p"
	.string "My name isn't important, but the\n"
	.string "people I work for want to know about\l"
	.string "you and your little squad.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "Now then.\pWasting my time won't do you\nany good.\p"
	.string "$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "This you?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "Your name. Now.$"


gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?\p"
	.string "$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "That better be the truth, because\nwe WILL find out if you're lying.\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Now then, {PLAYER}{KUN}.\p"
	.string "Why don't we start at the beginning...\p"
	.string "$"
